crypto-api {
  kafka {
    bootstrap-servers = "localhost:9092"
    group-id = "crypto-api-group"
    topic = "crypto-alerts"
  }
  database {
    driver = "org.postgresql.Driver"
    url = "jdbc:postgresql://localhost:5433/crypto_db"
    user = "admin"
    password = "password"
  }
  server {
    host = "0.0.0.0"
    port = 8080
  }
}