crypto-processor {
  kafka-consumer {
    bootstrap-servers = "localhost:9092"
    group-id = "crypto-analytics-group"
    topic = "crypto-prices-raw"
  }
  kafka-producer {
    bootstrap-servers = "localhost:9092"
    group-id = "crypto-producer-group"
    topic = "crypto-alerts"
  }
  # Порог изменения цены (например, 0.001 = 0.1% для тестов, чтобы алерты стреляли чаще)
  change-threshold = 0.001
}