crypto-ingestor {
    kafka {
        bootstrap-servers = "localhost:9092"
        group-id = "ingestor-group"
        topic = "crypto-prices-raw"
    }
    symbols = ["BTCUSDT", "ETHUSDT", "SOLUSDT", "DOGEUSDT"]
    poll-interval = 5s
}